# Generated by Django 3.2.5 on 2022-04-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_question_text_question_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse1', models.CharField(max_length=200)),
                ('adresse2', models.CharField(max_length=200)),
                ('adresse3', models.CharField(max_length=200)),
                ('telephone', models.IntegerField(default=0)),
                ('mail', models.CharField(max_length=200)),
            ],
        ),
    ]
