# Generated by Django 3.2.5 on 2022-04-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20220427_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='interlocuteur',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
