# Generated by Django 3.2.5 on 2022-04-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20220427_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='interlocuteur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
