# Generated by Django 3.2.5 on 2022-04-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20220427_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse3',
            field=models.CharField(blank=True, default='_', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='interlocuteur',
            field=models.CharField(blank=True, default='_', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.CharField(blank=True, default='_', max_length=200, null=True),
        ),
    ]
