# Generated by Django 3.2.5 on 2022-04-28 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20220427_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mission', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RefClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_client', models.CharField(max_length=200)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.client')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_facture', models.IntegerField()),
                ('date_edit', models.DateTimeField(verbose_name='date edition')),
                ('activite', models.CharField(max_length=200)),
                ('montant_HT', models.IntegerField(default=0)),
                ('remb_frais', models.IntegerField(blank=True, default=0, null=True)),
                ('taux_TVA', models.IntegerField(blank=True, default=0, null=True)),
                ('montant_TVA', models.IntegerField(blank=True, default=0, null=True)),
                ('montant_TTC', models.IntegerField(default=0)),
                ('statut', models.CharField(max_length=200)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.client')),
                ('id_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mission')),
                ('id_refclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.refclient')),
            ],
        ),
    ]
