# Generated by Django 3.2.5 on 2022-04-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20220428_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
