# Generated by Django 3.2.5 on 2022-04-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_client_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200)),
                ('date_creation', models.DateTimeField(verbose_name='date creation')),
                ('adresse1', models.CharField(max_length=200)),
                ('adresse2', models.CharField(max_length=200)),
                ('cp_ville', models.CharField(blank=True, default='_', max_length=200, null=True)),
                ('siren', models.IntegerField(blank=True, default=0, null=True)),
                ('siret', models.IntegerField(blank=True, default=0, null=True)),
                ('num_tva_intra', models.IntegerField(blank=True, default=0, null=True)),
                ('code_naf', models.IntegerField(blank=True, default=0, null=True)),
                ('capital_social', models.IntegerField(blank=True, default=0, null=True)),
                ('representant', models.CharField(blank=True, default='_', max_length=200, null=True)),
                ('telephone', models.IntegerField(blank=True, default=0, null=True)),
                ('mail', models.CharField(blank=True, default='_', max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='adresse3',
            new_name='cp_ville',
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='id_societe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.societe'),
        ),
    ]
