# Generated by Django 3.2.5 on 2022-04-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20220428_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='num_tva_intra',
            field=models.CharField(blank=True, default=0, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='siren',
            field=models.CharField(blank=True, default=0, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='siret',
            field=models.CharField(blank=True, default=0, max_length=14, null=True),
        ),
    ]
