# Generated by Django 3.2.5 on 2022-04-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20220428_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='code_naf',
            field=models.CharField(blank=True, default=0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='mail',
            field=models.CharField(blank=True, default='_', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='telephone',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
