# Generated by Django 3.2.5 on 2022-05-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20220501_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='adresse2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
